name: Run GBF Suite, Build Documentation, and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Run on pushes to `main`
      - dev   # Run on pushes to `dev`
permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS Credentials (if needed for external storage)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      # Step 4: Run GBF Suite
      - name: Run GBF Suite
        env:
          GBF_SUITE_DIR: ./gbf_core/tests/gs2bc/
        run: cargo run --package gbf_suite