name: MSRV Check

on:
  push:  # Run on pushes to any branch
  pull_request:  # Run on all pull requests

jobs:
  msrv-check:
    name: Minimum Supported Rust Version Check
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Rust 1.61.0
      - name: Install MSRV (1.61.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.61.0
          override: true

      # Verify the project builds with MSRV
      - name: Build and Test with MSRV
        run: |
          cargo clean
          cargo build --workspace --all-targets
          cargo test --workspace --all-targets
