name: MSRV Check

on:
  push:
    branches:
      - main  # Run on pushes to `main`
      - dev   # Run on pushes to `dev`
  pull_request:
    branches:
      - main  # Run on pull requests targeting `main`
      - dev   # Run on pull requests targeting `dev`

jobs:
  msrv-check:
    name: Minimum Supported Rust Version Check
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Rust 1.81.0
      - name: Install MSRV (1.81.0)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.81.0
          toolchain: nightly
      
      # https://stackoverflow.com/questions/78629554/how-to-cache-cargo-packages-in-the-github-ci-workflow
      - name: "Cache cargo"
        id: cache-cargo
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          save-always: true
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      # Verify the project builds with MSRV
      - name: Build and Test with MSRV
        run: |
          cargo clean
          cargo build --workspace --all-targets
          cargo test --workspace --all-targets
