name: Deploy to Netlify
on:
  push:
    branches:
      - main  # Run on pushes to `main`
      - dev   # Run on pushes to `dev`
  pull_request:
    branches:
      - main  # Run on pull requests targeting `main`
      - dev   # Run on pull requests targeting `dev`
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Netlify Deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=./gbf_web
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
