name: Rust CI

on:
  push:
    branches:
      - main  # Run on pushes to `main`
  pull_request:
    branches:
      - main  # Run on pull requests targeting `main`

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run CI script
        run: IS_CI=true ./scripts/pre-commit.sh
