name: Version Check and Enforcement

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python and install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          args: python -m pip install toml semantic-version

      - name: Run version checks
        env:
          TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: python ./scripts/version.py