name: Version Bump on Renovate PRs

on:
  pull_request:
    branches:
      - dev

permissions:
  contents: write

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python and install dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r ./scripts/requirements.txt

      - name: Check if PR is from a Renovate branch
        run: |
          if [[ "${{ github.head_ref }}" != feature/renovate/* ]]; then
            echo "Skipping version bump: Not a Renovate PR"
            exit 0
          fi

      - name: Run version check script
        run: python ./scripts/version.py --bump patch

      - name: Commit version bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi
          git commit -m "chore: bump version for Renovate PR"
          git push origin HEAD:${{ github.head_ref }}
