name: Version Check and Enforcement

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run version checks
        env:
          TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: ./scripts/version-check.sh
